export const MAP_API_KEY = process.env.EXPO_PUBLIC_MAP_API_KEY;
export const RAPIDO_SECRET_KEY = process.env.EXPO_PUBLIC_RAPIDO_SECRET_KEY;
export const RAPIDO_STORAGE_ID = process.env.EXPO_PUBLIC_RAPIDO_STORAGE_ID;